pool:
  vmImage: 'ubuntu-latest'

container: ubuntu:18.04

steps:
- script: printenv
- task: prisma-cloud-compute-scan@3
  inputs:
    scanType: 'images'
    twistlockService: 'arkprismacloudazuredevops'
    artifact: 'myubuntu'